# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      # specify the version you desire here
      - image: circleci/node:11.9.0

        environment:
          NG_CLI_ANALYTICS: ci

    environment:
      NG_CLI_ANALYTICS: ci

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # let's install npm
      # - run: npm install --silent
      # # install angular cli latest globally
      # - run: sudo npm install -g @angular/cli@latest --silent
      # # update
      # - run: ng update
      # # ng build --prod
      # - run: ng build --prod

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # copy dist files to digitalocean
      # - run: ssh -o StrictHostKeyChecking=no mkdir -p /home/deploy/core/pwa/admin
      # - run: scp -o StrictHostKeyChecking=no -r ./dist/Borga/* deploy@ek-brandconsult.com://home/deploy/apps/borga
      ################ WARNING WARNING #####################
      # doing no strict host key check is a security rist to some extent.
      # But I haven't figured a way to add to ssh for both CI and DO to communicate without that
      # message popping up
